services:
  - type: web
    name: zunko-site
    runtime: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm run start
    envVars:
      - key: YOUTUBE_API_KEY
        sync: false
      - key: NODE_VERSION
        value: "22"
